general = {
  name = "${AIRPLAY_DEVICE_NAME}";
  interpolation = "soxr";
  output_backend = "${AIRPLAY_BACKEND}";
};

sessioncontrol = {
  allow_session_interruption = "yes";
};

alsa = {
  output_device = "default";
  # If an ALSA mixer control is detectable, this line is set:
  # mixer_control_name = "${AIRPLAY_MIXER_CONTROL_NAME}";
  # Otherwise shairport-sync falls back to software volume control automatically.
};
